Level 1/task 2
OksanaDenysenko/php-course pull request #1
Opened 2024-07-16 12:19 UTC by OksanaDenysenko

доброго вечора
я переглянув Вашу домашку
коментарі:
1. "\n" i "\r\n" - заміняєте спеціальною константою у PHP, яка позначає новий рядок.
      Замінила "\n" константою PHP_EOL, але тоді $substring = explode(PHP_EOL, $string); чомусь не правильно розділяє, видає 
       результат (["POST \/doc\/test HTTP\/1.1\nHost: shpp.me\nAccept: image ...]), а повинна (["POST \/doc\/test 
       HTTP\/1.1","Host: shpp.me", ...]). Може це через те, що в мене Windows?

2. питання з теорії PHP. Чому не варто використовувати for ( ...; $i < count(...); $i++) ?
   Можливо через постійний перерахунок кількості елементів count(...), це займає час і в динамічних масивах це може 
   призвести до помилок. Замінила на foreach.

3. давай зрозуміліші назви змінним. у файлі homework2.php незрозуміло що таке $substring, $firstSubstring, $sub
   $substring так і залишила, бо для мене це зрозуміла назва, коли функція приймає рядок $string, то $substring - це 
   розділення цього рядка на підрядки;    $firstSubstring замінила на $method_and_uri; $sub замінила на $value в циклі 
  foreach

2024-07-16 18:55 UTC, anton-moroz requested changes

2024-07-16 18:55 UTC, anton-moroz commented on myhomework2.php
>      $body=$substring[count($substring)-1];
before and after `=` add spaces

2024-07-16 18:55 UTC, anton-moroz commented on myhomework2.php
>      return array(
use `[]` instead of `array()`

2024-07-16 18:55 UTC, anton-moroz commented on myhomework2.php
> +    $method_and_uri = explode(" ",$substring[0]);
space after `,`

2024-07-16 18:57 UTC, anton-moroz commented
> 1. "\n" i "\r\n" - заміняєте спеціальною константою у PHP, яка позначає новий рядок.
>    Замінила "\n" константою PHP_EOL, але тоді $substring = explode(PHP_EOL, $string); чомусь не правильно розділяє, видає
>    результат (["POST /doc/test HTTP/1.1\nHost: shpp.me\nAccept: image ...]), а повинна (["POST /doc/test
>    HTTP/1.1","Host: shpp.me", ...]). Може це через те, що в мене Windows?
саме так

> 2. питання з теорії PHP. Чому не варто використовувати for ( ...; $i < count(...); $i++) ?
>    Можливо через постійний перерахунок кількості елементів count(...), це займає час і в динамічних масивах це може
>    призвести до помилок. Замінила на foreach.
правильно. можна просто оголосити змінну і присвоїти їй результат `count()`, але foreach теж підходить

> 3. давай зрозуміліші назви змінним. у файлі homework2.php незрозуміло що таке $substring, $firstSubstring, $sub
>    $substring так і залишила, бо для мене це зрозуміла назва, коли функція приймає рядок $string, то $substring - це
>    розділення цього рядка на підрядки;    $firstSubstring замінила на $method_and_uri; $sub замінила на $value в циклі
>    foreach

> коли функція приймає рядок $string, то $substring - це   розділення цього рядка на підрядки;
тоді не вистачає множини, щоб було `$substrings`

2024-07-17 09:43 UTC, OksanaDenysenko commented on myhomework2.php
> +    $method_and_uri = explode(" ",$substring[0]);
corrected

2024-07-17 10:17 UTC, OksanaDenysenko commented
Додала коментарі до функцій

2024-07-21 08:39 UTC, anton-moroz requested changes

2024-07-21 08:39 UTC, anton-moroz commented on myhomework2.php
> +    while ($line = fgets($f)) {
empty line before if, while, for etc and after them. (in general - before and after any code blocks)

2024-07-21 08:39 UTC, anton-moroz commented on myhomework2.php
> +        if (preg_match('/Content-Length: (\d+)/', $line, $m))
empty line

2024-07-21 08:39 UTC, anton-moroz commented on myhomework2.php
> +        if ($line == "\r\n")
empty line

2024-07-21 08:39 UTC, anton-moroz commented on myhomework2.php
> +    if ($toread > 0)
empty line

2024-07-21 08:39 UTC, anton-moroz commented on myhomework2.php
> +    return $store;
empty line before return, break, continue

2024-07-29 16:02 UTC, OksanaDenysenko commented on myhomework2.php
> +        if (preg_match('/Content-Length: (\d+)/', $line, $m))
added

2024-07-29 16:02 UTC, OksanaDenysenko commented on myhomework2.php
> +        if ($line == "\r\n")
added

2024-07-29 16:02 UTC, OksanaDenysenko commented on myhomework2.php
> +    if ($toread > 0)
added

2024-07-29 16:02 UTC, OksanaDenysenko commented on myhomework2.php
> +    return $store;
added

2024-07-31 10:17 UTC, anton-moroz requested changes

2024-07-31 10:17 UTC, anton-moroz commented on myhomework2.php
> +        if ($key > 0 && $key < count($substrings) - 2) { // Перевірка індексу
the calculation is done on every iteration... it's not efficient
use another loop for skipping this check `$key` > 0

2024-08-19 13:46 UTC, OksanaDenysenko commented on myhomework2.php
> +        if ($key > 0 && $key < count($substrings) - 2) { // Перевірка індексу
wrote a foreach loop without using $key

2024-08-26 05:58 UTC, anton-moroz requested changes

2024-08-26 05:58 UTC, anton-moroz commented on myhomework2.php
> +    $uri = $methodAndUri[1];
extra variables: `$method`, `$uri`, `$body`. just pass their values to where you use these three variables

2024-08-26 12:36 UTC, OksanaDenysenko commented on myhomework2.php
> +    $uri = $methodAndUri[1];
corected

2024-08-30 07:27 UTC, anton-moroz approved these changes

2024-09-12 17:39 UTC, merged