Level 2/router
OksanaDenysenko/php-course pull request #10
Opened 2024-08-12 19:30 UTC by OksanaDenysenko

2024-08-19 10:11 UTC, anton-moroz requested changes

2024-08-19 10:11 UTC, anton-moroz commented on back.loc/api/v2/router.php
> +        $id = $stmt->insert_id;
redundant variable

2024-08-22 09:56 UTC, OksanaDenysenko commented on back.loc/api/v2/db_conect.php
> +$config = require 'config.php';
corrected

2024-08-22 10:03 UTC, OksanaDenysenko commented on back.loc/api/v2/db_config.php
>  if ($conn->query($sql) === TRUE) {
replased with foreach

2024-08-22 11:18 UTC, OksanaDenysenko commented on back.loc/api/v2/router.php
> +switch ($action) {
replased

2024-08-22 11:19 UTC, OksanaDenysenko commented on back.loc/api/v2/router.php
> +        $id = $stmt->insert_id;
deleted

2024-08-22 11:22 UTC, OksanaDenysenko commented on back.loc/api/v2/router.php
> +        exit(json_encode(['error' => 'Incorrect password']));
added

2024-08-26 07:09 UTC, anton-moroz requested changes

2024-09-12 17:55 UTC, OksanaDenysenko commented on back.loc/api/v2/router.php
> +match ($action) {
Thanks!

2024-09-13 09:52 UTC, OksanaDenysenko commented on back.loc/api/v2/db_conect.php
> +
deleted

2024-09-14 14:10 UTC, anton-moroz approved these changes

2024-09-14 15:02 UTC, closed without merging