Level 1/task 3
OksanaDenysenko/php-course pull request #2
Opened 2024-07-16 17:36 UTC by OksanaDenysenko

4. як можна замінити наступний код одним рядком? (використовуючи вбудовані функції)
$sum=0;
for($i=0; $i<count($numbers); $i++){
  $sum=$sum+$numbers[$i];
}
   
    Замінила на $sum = array_sum($numbers);

5. якщо можна не робити вкладені if - краще не робити. це додає складності у розумінні код (homework3.php, функція - processHttpRequest)
   
   Переписала без вкладеного if:
   if ($method !== "GET" || strpos($uri, "?nums=") === false || !is_array($numbers = explode(",", $subUri[1]))) {
    outputHttpResponse(400, "Bad Request", $headers, "not found");
    return;
    }

    if (strpos($uri, "/sum") !== 0) {
    outputHttpResponse(404, "Not Found", $headers, "not found");
    return;
    }
   $sum = array_sum($numbers);
   outputHttpResponse(200, "OK", $headers, $sum);

6. тут не вистачає методу запиту $response = "HTTP/1.1 " . $statuscode.$statusmessage.PHP_EOL;
   Може не правильно зрозуміла, де він повинен бути, але він є в рядку 23

2024-07-16 19:06 UTC, anton-moroz requested changes

2024-07-16 19:06 UTC, anton-moroz commented on myhomework3.php
> +    if (strpos($uri, "/sum") !== 0) { //uri не починається з /sum
є інша функція, яка краще підходить для такої перевірки

2024-07-16 19:06 UTC, anton-moroz commented on myhomework3.php
> +        return;
empty line before return

2024-07-17 11:34 UTC, OksanaDenysenko commented on myhomework3.php
> +    if (strpos($uri, "/sum") !== 0) { //uri не починається з /sum
replaced with (strncmp($uri, "/sum", 4) !==0)

2024-07-17 11:35 UTC, OksanaDenysenko commented on myhomework3.php
> +        return;
corrected

2024-07-21 08:44 UTC, anton-moroz requested changes

2024-07-21 08:44 UTC, anton-moroz commented on myhomework3.php
> +    $f = fopen('php://stdin', 'r');
same about styling as in previous PR

2024-07-21 08:44 UTC, anton-moroz commented on myhomework3.php
> +    if (strncmp($uri, "/sum", 4) !== 0) { //uri не починається з /sum
https://www.php.net/manual/en/function.str-starts-with.php

2024-07-21 08:44 UTC, anton-moroz commented on myhomework3.php
> +    if ($method !== "GET" || strpos($uri, "?nums=") === false || !is_array($numbers = explode(",", $subUri[1]))) {
https://www.php.net/manual/en/function.str-contains.php

2024-07-21 08:44 UTC, anton-moroz commented on myhomework3.php
> +    if ($method !== "GET" || strpos($uri, "?nums=") === false || !is_array($numbers = explode(",", $subUri[1]))) {
`!is_array($numbers = explode(",", $subUri[1]))`
explode will return you an array in any way. better to check amount of items in array and if the first element is not empty string

2024-07-29 16:59 UTC, OksanaDenysenko commented on myhomework3.php
> +    if (strncmp($uri, "/sum", 4) !== 0) { //uri не починається з /sum
replased

2024-07-29 16:59 UTC, OksanaDenysenko commented on myhomework3.php
> +    if ($method !== "GET" || strpos($uri, "?nums=") === false || !is_array($numbers = explode(",", $subUri[1]))) {
replased

2024-07-29 16:59 UTC, OksanaDenysenko commented on myhomework3.php
> +    if ($method !== "GET" || strpos($uri, "?nums=") === false || !is_array($numbers = explode(",", $subUri[1]))) {
replased

2024-07-31 11:17 UTC, anton-moroz requested changes

2024-07-31 11:17 UTC, anton-moroz commented on myhomework3.php
> +    if (!str_starts_with($uri, "/sum")) { //uri не починається з /sum
I believe it's better to make this check first

2024-08-19 13:59 UTC, OksanaDenysenko commented on myhomework3.php
> +    if (!str_starts_with($uri, "/sum")) { //uri не починається з /sum
rearranged

2024-08-19 14:00 UTC, OksanaDenysenko commented on myhomework3.php
> +    if ($method !== "GET" || !str_contains($uri, "?nums=") || count($numbers) < 1 || $numbers[0] == '') {
deleted

2024-08-26 06:01 UTC, anton-moroz approved these changes

2024-08-26 12:47 UTC, merged