Level 1/task 4
OksanaDenysenko/php-course pull request #4
Opened 2024-07-18 12:09 UTC by OksanaDenysenko

homework4.php
7.  цей код можна написати простіше. чекаю на ідеї / питання / реалізації
for($i=0; $i<count($string); $i++){
  if($string[$i]===$login_password){
     return outputHttpResponse(200," OK",$headers,"<h1 style=\"color:green\">FOUND</h1>");
  }
  if($i===(count($string)-1)){ // якщо логін і пароль не знайдені в файлику
    return outputHttpResponse(401," Unauthorized",$headers,"not found");
  }
}

Замінила на:
if ((strpos($string, $login_password)) !== false) {
      outputHttpResponse(200, " OK", $headers, "<h1 style=\"color:green\">FOUND</h1>");
 } else {
      outputHttpResponse(401, " Unauthorized", $headers, "not found");
 }

8.  у випадку помилки може бути виведено інформацію яка не потрібна юзеру. краще такі помилки логувати, а користувачу показувати повідомлення типу "Server error"
try {
  $fileContent = file_get_contents($file); // читаємо файл
} catch (Exception $e) {
  echo "Error: " . $e->getMessage();
}

Замінила на:
       try {
                $fileContent = file_get_contents($file); // читаємо файл
            } catch (Exception $e) {
                error_log("Error reading file: " . $e->getMessage(), 3);
                echo "Server error";
            }

2024-07-21 08:50 UTC, anton-moroz requested changes

2024-07-21 08:50 UTC, anton-moroz commented on myhomework4.php
> +    } else {
don't write nested constructions if that's not needed. It's hard to read and understand such code.
it's better to have 
```
if() {
  return;
}

if() {
  return;
}

```

2024-07-21 08:50 UTC, anton-moroz commented on myhomework4.php
> +                echo "Server error";
why not same `outputHttpResponse(500, " Integral Server Error", $headers, "not found");`?

2024-07-21 08:50 UTC, anton-moroz commented on myhomework4.php
> +        if ((strpos($string, $login_password)) !== false) {
empty line

2024-07-21 08:50 UTC, anton-moroz commented on myhomework4.php
> +        $string = explode("\n", $fileContent);
on explode you get array, not string

2024-07-21 08:50 UTC, anton-moroz commented on myhomework4.php
> +        if ((strpos($string, $login_password)) !== false) {
also this code will not works, because `$string` is array

2024-07-31 12:40 UTC, OksanaDenysenko commented on myhomework4.php
> +        $string = explode("\n", $fileContent);
corrected

2024-07-31 12:40 UTC, OksanaDenysenko commented on myhomework4.php
> +        if ((strpos($string, $login_password)) !== false) {
corrected

2024-07-31 12:40 UTC, OksanaDenysenko commented on myhomework4.php
> +                echo "Server error";
corrected

2024-07-31 12:40 UTC, OksanaDenysenko commented on myhomework4.php
> +    } else {
corrected

2024-08-26 06:12 UTC, anton-moroz commented on myhomework4.php
> +    $string = explode("\n", $fileContent);
it will work for small size files, but for bigger - not, because the memory will be exhausted

2024-08-26 06:14 UTC, anton-moroz requested changes

2024-08-26 06:14 UTC, anton-moroz commented on myhomework4.php
> +    $string = explode("\n", $fileContent);
don't load the whole file into memory
use streams to work with files

2024-08-31 08:07 UTC, anton-moroz approved these changes

2024-09-12 17:43 UTC, merged