Level 2/v1
OksanaDenysenko/php-course pull request #9
Opened 2024-07-28 17:35 UTC by OksanaDenysenko

Версія з авторизацією без SQL-ін'єкцій і XSS

2024-08-07 11:18 UTC, anton-moroz requested changes

2024-08-07 11:18 UTC, anton-moroz commented on back.loc/api/v1/register.php
> +$stmt = $conn->prepare("INSERT INTO users (login, pass) VALUES (?, ?)"); // prepared request
you don't handle in appropriate way a case when login is already taken

2024-08-07 11:18 UTC, anton-moroz commented on back.loc/api/v1/login.php
> +    setcookie('auth_token', $token, time() + 3600, '/'); // store the token in a cookie for 1 hour
it's a bad idea to store auth_token in a cookie in such a way...
better to pass it in header, or in secure read-only cookie
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#security

2024-08-07 11:18 UTC, anton-moroz commented on back.loc/api/v1/login.php
> +    setcookie('auth_token', $token, time() + 3600, '/'); // store the token in a cookie for 1 hour
and use one method, not both

2024-08-07 11:18 UTC, anton-moroz commented on back.loc/api/v1/login.php
> +    $token = bin2hex(random_bytes(32));
good solution

2024-08-07 11:18 UTC, anton-moroz commented on back.loc/api/v1/register.php
> +$hash_password =  password_hash($password, PASSWORD_DEFAULT); // Hashed password
I recommend to add several symbols to the password to increase password security

it's nice to hash the password, but users still can use very simple passwords, like "12345678". As far as I know, hashes for such passwords can be easily googled, so for hackers it's not a problem to guess that password

2024-08-13 10:47 UTC, OksanaDenysenko commented on back.loc/api/v1/addItem.php
> +$value_text=htmlspecialchars($text['text']);
added Strip_tags

2024-08-13 10:49 UTC, OksanaDenysenko commented on back.loc/api/v1/changeItem.php
> +$checked = $json["checked"]; //До $id і $checked не застосовую htmlspecialchars, бо ці поля, як я розумію, підтягуються автоматично
added 'Strip_tags' and 'htmlspecialchars' for $id and $checked

2024-08-13 10:54 UTC, OksanaDenysenko commented on back.loc/api/v1/db_config.php
> +$dbhost = "localhost";
the file "config.php" was created, where the data for connecting to the database is stored

2024-08-13 10:56 UTC, OksanaDenysenko commented on back.loc/api/v1/db_config.php
> +    echo "Database 'level2' successfully created" . PHP_EOL;
changed to "Database 'level2' exists"

2024-08-13 10:57 UTC, OksanaDenysenko commented on back.loc/api/v1/db_config.php
> +$sql = "CREATE TABLE IF NOT EXISTS items (
changed to "The items table exists"

2024-08-13 10:57 UTC, OksanaDenysenko commented on back.loc/api/v1/db_config.php
> +    echo "The users table was created successfully!" . PHP_EOL;
changed to "The users table exists"

2024-08-13 11:00 UTC, OksanaDenysenko commented on back.loc/api/v1/deleteItem.php
> + * Тут не робила підготовленого запиту і екранування спец.символів, бо користувач не вводить ніяких данних,
added

2024-08-13 11:25 UTC, OksanaDenysenko commented on back.loc/api/v1/deleteItem.php
> + *  а просто натичкає на хрестик і виконується код.
тобі нічого не заважає, а мені в голову такі ідеї не приходять :)

2024-08-13 11:26 UTC, OksanaDenysenko commented on back.loc/api/v1/getItems.php
> +$table="items";
deleted

2024-08-13 11:49 UTC, OksanaDenysenko commented on back.loc/api/v1/getItems.php
> +while ($row = $result->fetch_assoc()) {
replaced

2024-08-13 11:50 UTC, OksanaDenysenko commented on back.loc/api/v1/login.php
> +    $token = bin2hex(random_bytes(32));
Thanks! :)

2024-08-13 12:06 UTC, OksanaDenysenko commented on back.loc/api/v1/login.php
> +    setcookie('auth_token', $token, time() + 3600, '/'); // store the token in a cookie for 1 hour
replaced with setcookie('auth_token', $token, time() + 3600, '/', '', true, true);
В завдані написано використовувати і сесії і кукі, але якщо я правильно зрозуміла, то для авторизації користувача достатньо зберігати  auth_token в сесії. Чи так?

2024-08-13 12:12 UTC, OksanaDenysenko commented on back.loc/api/v1/register.php
> +$login = htmlspecialchars($data["login"]); // replacement of special characters with HTML entities
added

2024-08-13 12:12 UTC, OksanaDenysenko commented on back.loc/api/v1/register.php
> +$hash_password =  password_hash($password, PASSWORD_DEFAULT); // Hashed password
added

2024-08-13 12:14 UTC, OksanaDenysenko commented on back.loc/api/v1/register.php
> +$stmt = $conn->prepare("INSERT INTO users (login, pass) VALUES (?, ?)"); // prepared request
added a check in case when login is already taken

2024-08-13 12:30 UTC, OksanaDenysenko commented on back.loc/api/v1/.idea/php.xml
Я їх додаю, але вони чогось все одно не зникають..

2024-08-19 09:51 UTC, anton-moroz requested changes

2024-08-19 09:51 UTC, anton-moroz commented on .gitignore
> +back.loc/api/v1/.idea/
`back.loc/api/v1/.idea` or ` back.loc/api/v1/.idea/*`

2024-08-19 09:51 UTC, anton-moroz commented on back.loc/api/v1/addItem.php
> +$value_text=Strip_tags(htmlspecialchars($text['text']));
`Strip_tags` should be from small letter

2024-08-19 09:51 UTC, anton-moroz commented on back.loc/api/v1/db_config.php
> +$sql = "CREATE TABLE IF NOT EXISTS items (
same, if table was just created - the message should be "the table was created"

2024-08-19 09:51 UTC, anton-moroz commented on back.loc/api/v1/db_config.php
> +$sql = "CREATE TABLE IF NOT EXISTS items (
I will explain this thing on the call

2024-08-19 09:51 UTC, anton-moroz commented on back.loc/api/v1/getItems.php
> +$table="items";
I still see this variable

2024-08-19 09:51 UTC, anton-moroz commented on back.loc/api/v1/register.php
> +    echo json_encode(['error' => 'Database error']);
it's better not to show such messages - just "server error"

2024-08-19 09:51 UTC, anton-moroz commented on back.loc/api/v1/register.php
> +$stmt = $conn->prepare("INSERT INTO users (login, pass) VALUES (?, ?)"); // prepared request
your variant is a good solution. (frameworks use it for validation, for example Laravel. You will work with it and see it.)
initially I meant that user will try to take login "super_user", and if it's taken - user will see "database error" instead of "this login is taken".

you handled it, so `nice work! :)`

2024-08-22 11:24 UTC, OksanaDenysenko commented on back.loc/api/v1/register.php
> +$stmt = $conn->prepare("INSERT INTO users (login, pass) VALUES (?, ?)"); // prepared request
Thanks :)

2024-08-22 11:26 UTC, OksanaDenysenko commented on .gitignore
> +back.loc/api/v1/.idea/
back.loc/api/v1/.idea/
and I did this in other branches and it works

2024-08-22 11:27 UTC, OksanaDenysenko commented on back.loc/api/v1/addItem.php
> +$value_text=Strip_tags(htmlspecialchars($text['text']));
corrected

2024-08-26 06:55 UTC, anton-moroz requested changes

2024-08-26 06:55 UTC, anton-moroz commented on back.loc/api/v1/addItem.php
> +$value_text=strip_tags(htmlspecialchars($text['text']));
the result will not be such as you expect

2024-08-26 06:55 UTC, anton-moroz commented on back.loc/api/v1/changeItem.php
> +$stmt = $conn->prepare("UPDATE items SET text = ?, checked = '$checked' WHERE id = $id"); // prepared request
if `$checked` is string - a bad idea, if boolean - than it's better to store it as int

2024-08-26 06:55 UTC, anton-moroz commented on back.loc/api/v1/db_config.php
> +foreach ($arrCreateTables as $key =>$value){
just do `$table_name => $query` and don't make code complicated

2024-08-31 08:34 UTC, anton-moroz requested changes

2024-08-31 08:34 UTC, anton-moroz commented on back.loc/api/v1/addItem.php
> +
https://github.com/anton-moroz/php-code_styles

2024-08-31 08:34 UTC, anton-moroz commented on back.loc/api/v1/db_config.php
> +if ($conn->query($sql) === TRUE) {
`echo ($conn->query($sql) === TRUE ? "The database 'level2' was created" : "Error creating database: {$conn->error}") . PHP_EOL`

2024-08-31 08:34 UTC, anton-moroz commented on back.loc/api/v1/db_config.php
> +$arrCreateTables['items']=["CREATE TABLE items (
```
$arrCreateTables = [
	'items' => 'CREATE TABLE items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    text VARCHAR(255) NOT NULL,
    checked BOOL NOT NULL
)',
	'users' => 'CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    pass VARCHAR(255) NOT NULL
)'
];
```

2024-08-31 08:34 UTC, anton-moroz commented on back.loc/api/v1/db_config.php
> +    if ($conn->query($sql) === TRUE) {
also, you will get errors here, because `$sql` should be a string, but not array

2024-09-13 12:18 UTC, OksanaDenysenko commented on back.loc/api/v1/addItem.php
> +$value_text=strip_tags(htmlspecialchars($text['text']));
corrected
switched places  htmlspesialchars and strip_tags

2024-09-13 12:18 UTC, OksanaDenysenko commented on back.loc/api/v1/addItem.php
> +
corrected

2024-09-13 12:24 UTC, OksanaDenysenko commented on back.loc/api/v1/changeItem.php
> +$stmt = $conn->prepare("UPDATE items SET text = ?, checked = '$checked' WHERE id = $id"); // prepared request
corrected

2024-09-13 12:31 UTC, OksanaDenysenko commented on back.loc/api/v1/db_config.php
> +if ($conn->query($sql) === TRUE) {
Thanks, replased

2024-09-13 12:32 UTC, OksanaDenysenko commented on back.loc/api/v1/db_config.php
> +foreach ($arrCreateTables as $key =>$value){
Thanks, replased

2024-09-13 12:38 UTC, OksanaDenysenko commented on back.loc/api/v1/db_config.php
> +    if ($conn->query($sql) === TRUE) {
$sql will be a string, I checked it with var_dump ($sql =($arrCreateTables as $key =>$value) ). Now it is $query after replased

2024-09-14 14:07 UTC, anton-moroz approved these changes

2024-09-14 14:42 UTC, merged